language: php
sudo: false
dist: xenial

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - COMPOSER_MEMORY_LIMIT=-1

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - composer self-update

install:
  - composer update

script:
  - ./vendor/bin/phpunit -v

jobs:
  include:
    # Test against latest Symfony 4.3 stable
    - php: 7.3
      env: SYMFONY_REQUIRE="4.3.*"
      install:
        - composer update
        - composer show -i

    # Test against latest Symfony 4.4 dev
    - php: 7.3
      env: SYMFONY_REQUIRE="4.4.*"
      install:
        - composer update
        - composer show -i

    # Test against latest Symfony 5.0 dev
    - php: 7.3
      env: SYMFONY_REQUIRE="5.0.*"
      install:
        - composer update
        - composer show -i

    # Test dev versions
    - php: 7.3
      if: type = cron
      install:
        - composer update

    - stage: Code Quality
      php: 7.3
      script:
        - ./vendor/bin/phpcs

    - stage: Coverage
      php: 7.3
      install:
        - composer update
      before_script:
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      script:
        - ./vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml
